### ISSUE TITLE
ShieldedVMProvisioning Supporting Module

### ISSUE THREAD

**Issue by ghost** [Microsoft/GuardedFabricTools#1]
There seems to be a lack of documentation around the ShieldedVMProvisioning supporting module that this module utilizes. I also cannot find where to actually get the ShieldedVMProvisioning module to fully utilize this module. 

As an example just running the new-shieldedvm cmdlet will error on:

`Get-KeyProtectorFromShieldingDataFile : The term 'Get-KeyProtectorFromShieldingDataFile' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.`

Can you provide further clarification around the ShieldedVMProvisioning module and where to actually get this from. 

https://docs.microsoft.com/en-us/powershell/module/shieldedvmprovisioning/?view=win10-ps#shieldedvmprovisioning

**Comment by rpsqrd** [comment]
Hi @hector7869,

This module comes with Windows Server 2016 Datacenter Edition when you install the Host Guardian Hyper-V Support feature. This feature is required to provision shielded VMs using template disks and shielding data files.

```powershell
Install-WindowsFeature HostGuardian -IncludeAllSubFeature -Restart
```

Check out our [full documentation](https://docs.microsoft.com/en-us/windows-server/virtualization/guarded-fabric-shielded-vm/guarded-fabric-configure-hgs-with-authorized-hyper-v-hosts) for more information about required Hyper-V features and configuration.

Let me know if this helps!

Ryan

**Comment by ghost** [comment]
Thank you, that worked. BTW, I am working Windows 10 1709, which now has the HostGuardian feature.
