### ISSUE TITLE
Update module in PSGallery

### ISSUE THREAD

**Issue by comnam90** [Microsoft/GuardedFabricTools#3]
The version of these tools published to PSGallery are outdated and missing fixes, especially the ones around Static IPs

**Comment by rpsqrd** [comment]
@comnam90 a little late, but I'm happy to announce the PSGallery module is now updated with correct handling of static IPs (and a new, lightweight ConvertTo-ShieldedVM cmdlet if you don't want to go through the full provisoining process)
